package in.ineuron.main;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import in.ineuron.pojo.MobileCustomer;
import oracle.net.aso.c;

public class InsertAppBeforeVersioning
{
	public static void main(String[] args)
	{
		// CREATING Configuration Object
		Configuration config = new Configuration();
		config.configure("/in/ineuron/resources/hibernate.cfg.xml");

		// creating SessionFactory
		SessionFactory sessionFactory = config.buildSessionFactory();

		// creating session
		Session session = sessionFactory.openSession();

		// starting transaction
		Transaction tx = session.beginTransaction();

		// pojo
		MobileCustomer customer = new MobileCustomer();

		// primary key -> customer id is autogenerated
		customer.setcName("Safvan");
		customer.setMobNo("9895646120");
		customer.setCallerTune("Alif tune");
		// versioning is also automatic -> since we configured annotation

		int primaryKey = 0;
		boolean flag = false;

		try
		{
			primaryKey = (Integer) session.save(customer);
			tx.commit();
			flag = true;
		} catch (HibernateException e)
		{
			tx.rollback();
			flag = false;
			e.printStackTrace();
		} finally
		{
			if (flag)
			{
				System.err.println("object inserted successfully with auto Generated id :" + primaryKey);
				System.err.println(" version count after insertion : " + customer.getVesionCount());
			} else
				System.out.println("object insetion failed.......");
		}
	}
}
